18_Rails動画教材ページの実装
T-Tsujii/gyakuten_clone_group32 pull request #18
Opened 2020-10-22 14:07 UTC by Taiji-Namba

## 内容
- 動画一覧ページを作成
- ナビバーの動画教材ページへのリンクを機能

## 参考
https://arcane-gorge-21903.herokuapp.com/texts/218
https://arcane-gorge-21903.herokuapp.com/texts/211

2020-10-22 23:03 UTC, T-Tsujii commented on app/views/movies/index.html.erb
> +  <%= movie.url %>
これではURLしか表示されません。
YouTubeで動画ページの「共有」「埋め込む」からiframeタグの基本形を取得し，これにURLを入れる形式としましょう。

また，BootstrapのCardsを用いてなるべく近い形式にしてみましょう。レスポンシブ対応にもなっています。

2020-10-25 09:56 UTC, Taiji-Namba commented
## 修正箇所
- 一覧ページに動画埋め込み
- レスポンシブ対応
- 視聴済み/未視聴ボタン実装

## 参考資料
https://arcane-gorge-21903.herokuapp.com/texts/296
https://arcane-gorge-21903.herokuapp.com/texts/260
https://arcane-gorge-21903.herokuapp.com/texts/261
https://getbootstrap.com/docs/4.0/components/card/

2020-10-25 14:38 UTC, T-Tsujii requested changes

2020-10-25 14:38 UTC, T-Tsujii commented on app/views/movies/index.html.erb
> +<%= render "movies" %>
複数箇所で使用する予定がないのに，全てを部分テンプレートに入れてしまうと使用する意味がないでしょう。

2020-10-25 14:39 UTC, T-Tsujii commented
こちらのタスクでページネーションは実装予定でしょうか。

2020-10-25 14:45 UTC, Taiji-Namba commented
- _movies.html.erbを削除しました。
- ページネーションはタスク19でして頂く予定です。

2020-10-26 05:40 UTC, T-Tsujii approved these changes

2020-10-26 05:40 UTC, merged