追加_3 動画教材の進捗管理マイページ作成
T-Tsujii/gyakuten_clone_group32 pull request #23
Opened 2020-11-25 12:02 UTC by shogo2421

## 内容
- 進捗管理グラフの作成
- 進捗管理ページのスタイル修正

## 参考資料
- スタイル関係
https://www.design-memo.com/coding/css-stripe

- 進捗管理グラフ関係
https://qiita.com/nesheep5/items/d8716bcb97a89e19d4ce

2020-11-26 02:54 UTC, T-Tsujii requested changes

2020-11-26 02:54 UTC, T-Tsujii commented on app/controllers/mypages_controller.rb
> +    rails = 18..31
このようにidを指定してはいけません。データベースへの投入の仕方でidは変わってしまいます。もしidの配列を取得するならば，

```rb
basic_ids = Movie.where(genre: "Basic").order(id: :asc).ids
```

のようにすべきです。

なお，次のようななハッシュの配列を作り，ビュー側でeachの繰り返し処理で表示するのが理想的です。

```rb
[
  {
    genre: "Basic",
    total: "", # Basic教材の数
    current: "", # Basic教材の内，視聴済みの数
    percent: "" # Basic教材の視聴率
  },
  {
    genre: "Git",
    # 略
  },
]
```

2020-11-28 00:22 UTC, shogo2421 commented
- Movieテーブルにgenreカラムを追加

- 動画idの取得をwhereメソッドを用いた方法に変更

- 教材、視聴済みの数、視聴率の変数を減らすため、Genreクラスを作成

- ビューの表示にeachメソッドを使用

上記変更いたしました。よろしくお願いいたします。

2020-11-28 13:26 UTC, T-Tsujii requested changes

2020-11-28 13:26 UTC, T-Tsujii commented on app/controllers/mypages_controller.rb
> +    def initialize(genre_id)
`id` ではなく `ids` にすべきでしょう。

```suggestion
    def initialize(genre_ids)
```

2020-11-28 13:26 UTC, T-Tsujii commented on app/controllers/mypages_controller.rb
> +      @movies = genre_id.count
変数名と内容が一致していないので，修正すべきです。

```suggestion
      @total = genre_id.count
```

2020-11-28 13:26 UTC, T-Tsujii commented on app/controllers/mypages_controller.rb
> +      @percentage = viewing * 100 / movies
データが入っていない場合は分母が0になりますので，その対応もしておくべきです。

2020-11-28 13:26 UTC, T-Tsujii commented on app/controllers/mypages_controller.rb
> +    basic = Genre.new(basic_ids)
第2引数にgenreを入れ，initializeメソッドに@genreも定義しておけば，`@progress` をもっと簡潔にかけるはずです。

2020-11-29 10:38 UTC, shogo2421 commented
- genre_idをgenre_idsへ変更

- @percentageの分母が0の場合の時の処理を追加

- @moviesを@totalに変更

- Genreクラスinitializeメソッドに@genreを定義し、@progressを修正

上記変更いたしました。ご確認よろしくお願いいたします。

2020-11-29 10:43 UTC, T-Tsujii approved these changes
LGTMです！

2020-11-29 10:43 UTC, merged